USE Problema3

-- PROBLEM: Set the transaction isolation level REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRANSACTION
    SELECT * FROM Producatori
	WAITFOR DELAY '00:00:07'
	SELECT * FROM Producatori
COMMIT TRANSACTION

-- SOLUTION: Set the transaction isolation level SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION
    SELECT * FROM Producatori
	WAITFOR DELAY '00:00:07'
	SELECT * FROM Producatori
COMMIT TRANSACTION