USE Problema1

-- PROBLEM: Set the transaction isolation level READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

BEGIN TRANSACTION
    SELECT * FROM Tari
COMMIT TRANSACTION

-- SOLUTION: Set the transaction isolation level READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION
    SELECT * FROM Tari
COMMIT TRANSACTION