CREATE DATABASE Biscuiti;

GO
USE Biscuiti;

GO

CREATE TABLE LogTable0
(cod_log INT PRIMARY KEY IDENTITY,
mesaj VARCHAR(100)
);

CREATE TABLE Biscuiti0
(cod_b INT PRIMARY KEY IDENTITY,
nume_b VARCHAR(100),
nr_calorii INT,
pret REAL
);

CREATE TABLE Clienti0
(cod_c INT PRIMARY KEY IDENTITY,
nume_c VARCHAR(100)
);

CREATE TABLE Note0
(cod_b INT FOREIGN KEY REFERENCES Biscuiti0(cod_b)
ON UPDATE CASCADE ON DELETE CASCADE,
cod_c INT FOREIGN KEY REFERENCES Clienti0(cod_c)
ON UPDATE CASCADE ON DELETE CASCADE,
nota INT,
CONSTRAINT pk_Note PRIMARY KEY (cod_b, cod_c)
);