USE Problema2

-- PROBLEM: Set the transaction isolation level READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION
    SELECT * FROM Clasamente
	WAITFOR DELAY '00:00:07'
	SELECT * FROM Clasamente
COMMIT TRANSACTION

-- SOLUTION: Set the transaction isolation level REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRANSACTION
    SELECT * FROM Clasamente
	WAITFOR DELAY '00:00:07'
	SELECT * FROM Clasamente
COMMIT TRANSACTION